/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 VolvoCar.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const zPlane = new THREE.Plane(new THREE.Vector3(0, 0, 1), 0);
const yPlane = new THREE.Plane(new THREE.Vector3(0, 1, 0), 1);

export function VolvoCar(props) {
	const { nodes, materials } = useGLTF("/models/VolvoCar.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
				<mesh
					geometry={nodes.Volvo_EX30_2023_1.geometry}
					// material={materials.chrome}
				>
					<meshBasicMaterial
						{...materials.chrome}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_2.geometry}
					// material={materials.interior}
				>
					<meshBasicMaterial
						{...materials.interior}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_3.geometry}
					// material={materials.black}
				>
					<meshBasicMaterial
						{...materials.black}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_4.geometry}
					// material={materials.carpaint}
				>
					<meshBasicMaterial
						{...materials.carpaint}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_5.geometry}
					// material={materials.windowglass}
				>
					<meshBasicMaterial
						{...materials.windowglass}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_6.geometry}
					// material={materials.clearglass}
				>
					<meshBasicMaterial
						{...materials.clearglass}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_7.geometry}
					// material={materials.darkglass}
				>
					<meshBasicMaterial
						{...materials.darkglass}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_8.geometry}
					// material={materials.redglass}
				>
					<meshBasicMaterial
						{...materials.redglass}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_9.geometry}
					// material={materials.mirror}
				>
					<meshBasicMaterial
						{...materials.mirror}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_10.geometry}
					// material={materials.rim_second}
				>
					<meshBasicMaterial
						{...materials.rim_second}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_11.geometry}
					// material={materials.rim}
				>
					<meshBasicMaterial
						{...materials.rim}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_12.geometry}
					// material={materials.tire}
				>
					<meshBasicMaterial
						{...materials.tire}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_13.geometry}
					// material={materials.brakedisk}
				>
					<meshBasicMaterial
						{...materials.brakedisk}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				{/* <mesh
					geometry={nodes.Volvo_EX30_2023_14.geometry}
					// material={materials.LicPlate_white}
				>
					<meshBasicMaterial
						{...materials.LicPlate_white}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_15.geometry}
					// material={materials.LicPlate_black}
				>
					<meshBasicMaterial
						{...materials.LicPlate_black}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_16.geometry}
					// material={materials.LicPlate_blue}
				>
					<meshBasicMaterial
						{...materials.LicPlate_blue}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh>
				<mesh
					geometry={nodes.Volvo_EX30_2023_17.geometry}
					// material={materials.LicPlate_yellow}
				>
					<meshBasicMaterial
						{...materials.LicPlate_yellow}
						side={THREE.DoubleSide}
						clippingPlanes={props.clip ? [zPlane, yPlane] : null}
					/>
				</mesh> */}
			</group>
		</group>
	);
}

useGLTF.preload("/models/VolvoCar.glb");
