/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 volvo.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VolvoNew(props) {
	const { nodes, materials } = useGLTF("/models/volvo-new/volvo.gltf");
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]} scale={0.234}>
				<mesh
					geometry={nodes.Volvo_EX30_2023_1.geometry}
					material={materials["chrome.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_2.geometry}
					material={materials["interior.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_3.geometry}
					material={materials["black.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_4.geometry}
					material={materials["carpaint.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_5.geometry}
					material={materials["windowglass.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_6.geometry}
					material={materials["clearglass.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_7.geometry}
					material={materials["darkglass.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_8.geometry}
					material={materials["redglass.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_9.geometry}
					material={materials["mirror.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_10.geometry}
					material={materials["rim_second.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_11.geometry}
					material={materials["rim.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_12.geometry}
					material={materials["tire.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_13.geometry}
					material={materials["brakedisk.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_14.geometry}
					material={materials["LicPlate_white.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_15.geometry}
					material={materials["LicPlate_black.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_16.geometry}
					material={materials["LicPlate_blue.001"]}
				/>
				<mesh
					geometry={nodes.Volvo_EX30_2023_17.geometry}
					material={materials["LicPlate_yellow.001"]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/models/volvo-new/volvo.gltf");
